name: 'First Action'

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: TechDay
  testvar: value-global

jobs:
  mainJob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Hello
      testvar: value-job

    steps:
      - name: 'Print-values-of-env-vars'
        run: |
          echo "$Greeting $First_Name.Today is $DAY_OF_WEEK!"
          echo "testvar $testvar"
          echo "testvar ${{env.testvar}}"
        env:
          First_Name: Subscribers
          testvars: value-step
