name: 'Secret Test'
on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print Secret'
        run: |
          echo 'APP_SERET: ${{secrets.APP_SECRET}}'
          echo 'NO_SECRT: ${{secrets.NO_SECRET}}'
      - name: 'Print secret as environment variable'
        run: |
          echo "APP_SECRET: $USE_SECRET"
        env:
          USE_SECRET: ${{secrets.APP_SECRET}}
